import { useEffect, useState } from 'react'
import { CircleAlert, ExternalLink, FileCheck2, RefreshCw } from 'lucide-react'
import { useParams } from 'react-router-dom'
import { Header } from '@/components/layout'
import { Alert, AlertDescription, AlertTitle } from '@/components/ui/alert'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { normalizeProviderTarget } from '@/lib/providers'
import { normalizeCarCheck, phase4Status, type CarCheckV1 } from '@/lib/phase4'

export default function Car() {
  const { cid: rawCid = '' } = useParams<{ cid: string }>(); const [cid, setCid] = useState(''); const [data, setData] = useState<CarCheckV1 | null>(null); const [error, setError] = useState(''); const [loading, setLoading] = useState(true)
  async function load(target: string) { setLoading(true); setError(''); try { const response = await fetch(`/_rainbow/api/v1/car/check?cid=${encodeURIComponent(target)}`, { headers: { Accept: 'application/json' } }); const body = await response.json().catch(() => null); if (!response.ok) throw new Error(body?.error?.code || `HTTP ${response.status}`); const normalized = normalizeCarCheck(body); if (!normalized) throw new Error('invalid_response'); setData(normalized) } catch (caught) { setError(caught instanceof Error ? caught.message : 'unavailable') } finally { setLoading(false) } }
  useEffect(() => { try { const target = normalizeProviderTarget(rawCid); setCid(target); void load(target) } catch { setError('invalid_cid'); setLoading(false) } }, [rawCid])
  return <div className="flex min-h-svh flex-col"><Header /><main className="mx-auto w-full max-w-5xl flex-1 px-6 py-10"><div className="flex items-center gap-2 text-sm text-muted-foreground"><FileCheck2 className="size-4" /> CAR check</div><h1 className="mt-3 break-all text-2xl font-semibold tracking-tight">{cid || rawCid}</h1>{error && <Alert className="mt-6" variant="destructive"><CircleAlert className="size-4" /><AlertTitle>Could not check CAR</AlertTitle><AlertDescription>{error.replaceAll('_', ' ')}. {cid && <Button variant="link" className="h-auto p-0" onClick={() => void load(cid)}><RefreshCw className="size-3" /> Retry</Button>}</AlertDescription></Alert>}{loading && <div className="mt-6 h-40 animate-pulse rounded-md bg-muted" />}{!loading && !error && data && <Card className="mt-6"><CardHeader><div className="flex flex-wrap items-center justify-between gap-3"><CardTitle className="text-base">Verification result</CardTitle><Badge variant="outline">{phase4Status(data.verification.status)}</Badge></div></CardHeader><CardContent><dl className="grid gap-5 sm:grid-cols-2 lg:grid-cols-4"><div><dt className="text-xs text-muted-foreground">Scope</dt><dd>{data.verification.scope}</dd></div><div><dt className="text-xs text-muted-foreground">CAR version</dt><dd>{data.verification.carVersion || 'Not reported'}</dd></div><div><dt className="text-xs text-muted-foreground">Root declared match</dt><dd>{data.verification.declaredRootMatches === undefined ? 'Not reported' : data.verification.declaredRootMatches ? 'Yes' : 'No'}</dd></div><div><dt className="text-xs text-muted-foreground">Root block</dt><dd>{data.verification.rootBlockPresent === undefined ? 'Not reported' : data.verification.rootBlockPresent ? 'Present' : 'Missing'}</dd></div><div><dt className="text-xs text-muted-foreground">Root block verified</dt><dd>{data.verification.rootBlockVerified === undefined ? 'Not reported' : data.verification.rootBlockVerified ? 'Yes' : 'No'}</dd></div><div><dt className="text-xs text-muted-foreground">Blocks read</dt><dd>{data.verification.blocksRead ?? 'Not reported'}</dd></div><div><dt className="text-xs text-muted-foreground">Bytes read</dt><dd>{data.verification.bytesRead ?? 'Not reported'}</dd></div></dl><p className="mt-5 text-sm text-muted-foreground">This result does not prove DAG completeness.</p><Button asChild variant="outline" size="sm" className="mt-4"><a href={`/ipfs/${cid}?format=car`}><ExternalLink className="size-4" />Open CAR response</a></Button></CardContent></Card>}</main></div>
}
